# Generated by Django 3.0.5 on 2020-04-28 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_apprentice', models.BooleanField(null=True)),
                ('is_supervisor', models.BooleanField(null=True)),
                ('email_validated', models.BooleanField(default=False)),
                ('mobile_validated', models.BooleanField(default=False)),
                ('mailing_address_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('mailing_street1', models.CharField(max_length=50)),
                ('mailing_street2', models.CharField(blank=True, max_length=50, null=True)),
                ('mailing_city', models.CharField(max_length=50)),
                ('mailing_state', models.CharField(max_length=50)),
                ('signature', models.ImageField(default='signature_default.png', upload_to='signatures')),
                ('practitioner_dba', models.CharField(max_length=50, null=True)),
                ('profile_image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprenticeSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profile_active', models.BooleanField(default=True)),
                ('pre_number', models.CharField(default='Not Entered', max_length=20, null=True)),
                ('professional_license_number', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_profile_active', models.BooleanField(default=True)),
                ('has_discipline', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
            ],
        ),
    ]
