# Generated by Django 3.0.5 on 2020-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mailing_street2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
