# Generated by Django 3.0.5 on 2020-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apprentice',
            name='has_discipline',
        ),
        migrations.RemoveField(
            model_name='apprentice',
            name='is_profile_active',
        ),
        migrations.RemoveField(
            model_name='apprenticesupervisor',
            name='is_profile_active',
        ),
        migrations.RemoveField(
            model_name='apprenticesupervisor',
            name='pre_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='establishment_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_discipline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_profile_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_license_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
