const FETCH_POSTS = 'FETCH_POSTS'
const NEW_POST = 'NEW_POST'
const FETCH_JSONWEBTOKEN = 'FETCH_JSONWEBTOKEN'
const ALERT_INFO = 'ALERT_INFO'
const ALERT_SUCCESS = 'ALERT_SUCCESS'
const ALERT_ERROR = 'ALERT_ERROR'
const GET_ERRORS = 'GET_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'







export {
    ALERT_INFO,
    ALERT_SUCCESS,
    ALERT_ERROR,
    CLEAR_ERRORS,
    GET_ERRORS,
    FETCH_POSTS, 
    NEW_POST, 
    FETCH_JSONWEBTOKEN,
}