const FETCH_POSTS = 'FETCH_POSTS'
const NEW_POST = 'NEW_POST'
const FETCH_JSONWEBTOKEN = 'FETCH_JSONWEBTOKEN'
const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
const GET_DOCS = 'GET_DOCS'
const ADD_DOC = 'ADD_DOC'
const UPDATE_DOC = 'UPDATE_DOC'
const GET_USER = 'GET_USER'
const VIEW_INBOX = 'VIEW_INBOX'
const NEW_MAIL = 'NEW_MAIL'
const DELETE_MAIL = 'DELETE_MAIL'
const GET_ALERTS = 'GET_ALERTS'








export {
	FETCH_POSTS, 
	NEW_POST, 
	FETCH_JSONWEBTOKEN, 
	USER_AUTHENTICATED,
	GET_DOCS,
	ADD_DOC,
	UPDATE_DOC,
	GET_USER,
	VIEW_INBOX,
	NEW_MAIL,
	DELETE_MAIL,
	GET_ALERTS,
}
