"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import django_heroku

CSRF_TRUSTED_ORIGINS = ['http://localhost','127.0.0.1','http://localhost:3000','127.0.0.1:3000']
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9$tfgzgbxbr_b%e^2+txd98!_^0i&4^+ai33v2ey@(7s%4-r!s'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['http://localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django_extensions',
    ######### MY APPS ##########
    'corsheaders',
    'rest_framework',
    # 'django_restframework',
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'user_chats.apps.UserChatsConfig',
    ######### CHANNELS / PUSH NOTIFICATIONS ##########
    'channels', 
    # ######### WORKFLOW ##########
    # 'lbattachment',
    # 'lbworkflow',
    # 'lbadminlte',
    # 'lbutils',
    # 'compressor',
    # 'djangobower',
    # 'el_pagination',
    # 'stronghold',

]

MIDDLEWARE = [
    
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ######### WORKFLOW ##########
    # 'stronghold.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            'TEST': {
            'NAME': os.path.join(BASE_DIR, 'db_test.sqlite3')
        }
    },

}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'

# SERVING STATIC FILES FROM CLOUD OR CDN IF USING THIS OPTION RUN f"django-admin collectstatic"
#### STATICFILES_STORAGE = 'myproject.storage.S3Storage'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = 'blog-home'
LOGIN_URL = 'login'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

django_heroku.settings(locals())
# ###Instead of sending out real emails the console backend just writes the emails that would be sent to the standard output.###
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_CLASS_CONVERTERS = {'textinput': "textinput inputtext"}
############ DJANGO REST-FRAMEWORK ############

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}
############ DJANGO CHANNELS ############
### couldn't get docker to run for this backend 'channels_redis.core.RedisChannelLayer'
ASGI_APPLICATION = "django_project.routing.application"
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
CHANNEL_LAYERS = {
    'default': {
        # "ENGINE": "channels.layers.InMemoryChannelLayer",
        'BACKEND':  "channels_redis.core.RedisChannelLayer",
        'CONFIG': {
            "hosts": [("localhost", 6379,),],
            "symmetric_encryption_keys": [SECRET_KEY],
            },
    },
}
REDIS_HOST = 'localhost'
REDIS_PORT = 6379